### ISSUE TITLE
Using domed port covers.

### ISSUE THREAD

**Issue by ChristianWesterdahl** [ntnu-arl/reaqrovio#1]
In the associated paper, and I would also assume this implementation, you describe the that the camera is located directly behind a thin (2.5 mm) flat port waterproof casing lens. The refractive distortion through this is modeled by **g**_r in the paper.

We would very much like to use ReAqROVIO in a setting with a stereo camera, where both cameras are positioned behind glass domes, with the camera lens directly in the centre of the dome. Theoretically, this would eliminate any refractive distortion from the glass window. Is this as easy as to set the `refractiveCalibration` 
and `useObservabilityCheck` both to false?

**Comment by Mohit505Git** [comment]
Yes, for dome ports with cameras at the geometric center, the refractive effects are absent (theoretically). Thus, just setting `refractiveCalibration` and `useObservabilityCheck` to false with refractive_index to 1.0 is enough.
